-- Create users table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create groups table
CREATE TABLE groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create user_groups table to establish many-to-many relationship
CREATE TABLE user_groups (
  user_id INT,
  group_id INT,
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE
);

-- Insert initial data into users table
-- In here I choose to use Grouped Insert - Single Insert
INSERT INTO users (name, email) VALUES 
('John Doe', 'john@example.com'),
('Jane Smith', 'jane@example.com'),
('Alice Johnson', 'alice.johnson@example.com'),
('Bob Williams', 'bob.williams@example.com'),
('Charlie Brown', 'charlie.brown@example.com'),
('Diana Evans', 'diana.evans@example.com'),
('Ethan Clark', 'ethan.clark@example.com'),
('Fiona Harris', 'fiona.harris@example.com'),
('George Lewis', 'george.lewis@example.com'),
('Hannah Walker', 'hannah.walker@example.com'),
('Ian Robinson', 'ian.robinson@example.com'),
('Julia Hall', 'julia.hall@example.com'),
('Kevin Allen', 'kevin.allen@example.com'),
('Laura Young', 'laura.young@example.com'),
('Michael King', 'michael.king@example.com'),
('Nina Scott', 'nina.scott@example.com'),
('Oliver Adams', 'oliver.adams@example.com'),
('Paula Baker', 'paula.baker@example.com'),
('Quentin Mitchell', 'quentin.mitchell@example.com'),
('Rachel Carter', 'rachel.carter@example.com'),
('Samuel Perez', 'samuel.perez@example.com'),
('Tina Roberts', 'tina.roberts@example.com'),
('Ulysses Turner', 'ulysses.turner@example.com'),
('Victoria Phillips', 'victoria.phillips@example.com'),
('William Campbell', 'william.campbell@example.com'),
('Xenia Parker', 'xenia.parker@example.com'),
('Yusuf Morris', 'yusuf.morris@example.com'),
('Aaron Bennett', 'aaron.bennett@example.com'),
('Abigail Foster', 'abigail.foster@example.com'),
('Adam Simmons', 'adam.simmons@example.com'),
('Adrian Perry', 'adrian.perry@example.com'),
('Alexandra Butler', 'alexandra.butler@example.com'),
('Amber Brooks', 'amber.brooks@example.com'),
('Andrew Ross', 'andrew.ross@example.com'),
('Angela Long', 'angela.long@example.com'),
('Anthony Price', 'anthony.price@example.com'),
('Arthur Hughes', 'arthur.hughes@example.com'),
('Ashley Coleman', 'ashley.coleman@example.com'),
('Austin Myers', 'austin.myers@example.com'),
('Barbara Jenkins', 'barbara.jenkins@example.com'),
('Benjamin Gray', 'benjamin.gray@example.com'),
('Beverly James', 'beverly.james@example.com'),
('Bradley Watson', 'bradley.watson@example.com'),
('Brandon Sanders', 'brandon.sanders@example.com'),
('Brenda Wood', 'brenda.wood@example.com'),
('Brian Barnes', 'brian.barnes@example.com'),
('Brittany Kelly', 'brittany.kelly@example.com'),
('Caleb Henderson', 'caleb.henderson@example.com'),
('Cameron Patterson', 'cameron.patterson@example.com'),
('Carl Simmons', 'carl.simmons@example.com'),
('Carolyn Ramirez', 'carolyn.ramirez@example.com'),
('Catherine Ward', 'catherine.ward@example.com'),
('Chad Peterson', 'chad.peterson@example.com'),
('Chelsea Bryant', 'chelsea.bryant@example.com'),
('Christian Alexander', 'christian.alexander@example.com'),
('Christopher Russell', 'christopher.russell@example.com'),
('Claire Griffin', 'claire.griffin@example.com'),
('Cody Hayes', 'cody.hayes@example.com'),
('Colin Myers', 'colin.myers@example.com'),
('Connor Ford', 'connor.ford@example.com'),
('Courtney Hamilton', 'courtney.hamilton@example.com'),
('Curtis Graham', 'curtis.graham@example.com'),
('Cynthia Sullivan', 'cynthia.sullivan@example.com'),
('Daniel Wallace', 'daniel.wallace@example.com'),
('Danielle Cole', 'danielle.cole@example.com'),
('David West', 'david.west@example.com'),
('Deborah Jordan', 'deborah.jordan@example.com'),
('Dennis Reynolds', 'dennis.reynolds@example.com'),
('Derek Fisher', 'derek.fisher@example.com'),
('Dominic Knight', 'dominic.knight@example.com'),
('Donald Gibson', 'donald.gibson@example.com'),
('Donna Stevens', 'donna.stevens@example.com'),
('Douglas Rice', 'douglas.rice@example.com'),
('Dylan Webb', 'dylan.webb@example.com'),
('Edward Murray', 'edward.murray@example.com'),
('Eleanor Palmer', 'eleanor.palmer@example.com'),
('Elizabeth Wells', 'elizabeth.wells@example.com'),
('Emily Porter', 'emily.porter@example.com'),
('Eric Shaw', 'eric.shaw@example.com'),
('Erica Holmes', 'erica.holmes@example.com'),
('Evelyn Wagner', 'evelyn.wagner@example.com'),
('Franklin Gordon', 'franklin.gordon@example.com'),
('Gabriel Hicks', 'gabriel.hicks@example.com'),
('Gary Crawford', 'gary.crawford@example.com'),
('Gavin Boyd', 'gavin.boyd@example.com'),
('Grace Mason', 'grace.mason@example.com'),
('Gregory Olson', 'gregory.olson@example.com'),
('Heather Hunt', 'heather.hunt@example.com'),
('Henry Black', 'henry.black@example.com'),
('Holly Robertson', 'holly.robertson@example.com'),
('Isaac Mills', 'isaac.mills@example.com'),
('Isabella Howell', 'isabella.howell@example.com'),
('Jack Weaver', 'jack.weaver@example.com'),
('Jacob Ryan', 'jacob.ryan@example.com'),
('James Daniels', 'james.daniels@example.com'),
('Jared Garrett', 'jared.garrett@example.com'),
('Jason Snyder', 'jason.snyder@example.com'),
('Jeffrey Welch', 'jeffrey.welch@example.com'),
('Jeremy Burke', 'jeremy.burke@example.com'),
('Jessica Larson', 'jessica.larson@example.com'),
('Joel Meyer', 'joel.meyer@example.com'),
('Jonathan Duncan', 'jonathan.duncan@example.com'),
('Jordan Ferguson', 'jordan.ferguson@example.com'),
('Josephine Davidson', 'josephine.davidson@example.com'),
('Joshua Harrison', 'joshua.harrison@example.com'),
('Justin Carpenter', 'justin.carpenter@example.com'),
('Katherine May', 'katherine.may@example.com'),
('Keith Yates', 'keith.yates@example.com'),
('Kelly Simmons', 'kelly.simmons@example.com'),
('Kenneth Foster', 'kenneth.foster@example.com'),
('Kimberly Willis', 'kimberly.willis@example.com'),
('Kyle Jordan', 'kyle.jordan@example.com'),
('Lawrence Banks', 'lawrence.banks@example.com'),
('Leslie Little', 'leslie.little@example.com'),
('Logan Chapman', 'logan.chapman@example.com'),
('Louis Fox', 'louis.fox@example.com'),
('Lucas George', 'lucas.george@example.com'),
('Marcus Lane', 'marcus.lane@example.com'),
('Margaret Riley', 'margaret.riley@example.com'),
('Mariah Harper', 'mariah.harper@example.com'),
('Mark Cunningham', 'mark.cunningham@example.com'),
('Mary Hopkins', 'mary.hopkins@example.com'),
('Matthew Castro', 'matthew.castro@example.com'),
('Megan Chambers', 'megan.chambers@example.com'),
('Melanie Hanson', 'melanie.hanson@example.com'),
('Melissa Howell', 'melissa.howell@example.com'),
('Nathaniel Silva', 'nathaniel.silva@example.com');

-- Insert initial data into groups table
INSERT INTO groups (name, status) VALUES ('Admins', 'NotEmpty');
INSERT INTO groups (name, status) VALUES ('Users', 'NotEmpty');

-- Insert initial data into user_groups table
-- Here once again I choose to use Grouped Insert - Single Insert - Users 1 to 5 are Admins
INSERT INTO user_groups (user_id, group_id) VALUES 
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1),
(6, 2), (7, 2), (8, 2), (9, 2), (10, 2),
(11, 2), (12, 2), (13, 2), (14, 2), (15, 2),
(16, 2), (17, 2), (18, 2), (19, 2), (20, 2),
(21, 2), (22, 2), (23, 2), (24, 2), (25, 2),
(26, 2), (27, 2), (28, 2), (29, 2), (30, 2),
(31, 2), (32, 2), (33, 2), (34, 2), (35, 2),
(36, 2), (37, 2), (38, 2), (39, 2), (40, 2),
(41, 2), (42, 2), (43, 2), (44, 2), (45, 2),
(46, 2), (47, 2), (48, 2), (49, 2), (50, 2),
(51, 2), (52, 2), (53, 2), (54, 2), (55, 2),
(56, 2), (57, 2), (58, 2), (59, 2), (60, 2),
(61, 2), (62, 2), (63, 2), (64, 2), (65, 2),
(66, 2), (67, 2), (68, 2), (69, 2), (70, 2),
(71, 2), (72, 2), (73, 2), (74, 2), (75, 2),
(76, 2), (77, 2), (78, 2), (79, 2), (80, 2),
(81, 2), (82, 2), (83, 2), (84, 2), (85, 2),
(86, 2), (87, 2), (88, 2), (89, 2), (90, 2),
(91, 2), (92, 2), (93, 2), (94, 2), (95, 2),
(96, 2), (97, 2), (98, 2), (99, 2), (100, 2),
(101, 2), (102, 2), (103, 2), (104, 2), (105, 2),
(106, 2), (107, 2), (108, 2), (109, 2), (110, 2),
(111, 2), (112, 2), (113, 2), (114, 2), (115, 2),
(116, 2), (117, 2), (118, 2), (119, 2), (120, 2),
(121, 2), (122, 2), (123, 2), (124, 2), (125, 2),
(126, 2), (127, 2);